package com.jobhub.mockinterview.api;
import com.jobhub.mockinterview.application.MockInterviewService; import com.jobhub.mockinterview.domain.*; import jakarta.validation.constraints.NotBlank; import jakarta.validation.constraints.NotNull; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/mock-interviews") public class MockInterviewController { private final MockInterviewService s; public MockInterviewController(MockInterviewService x){s=x;}
 record Create(@NotBlank String projectId){} record Transition(@NotNull MockInterviewStatus targetStatus){} record Answer(@NotBlank @jakarta.validation.constraints.Size(max=10000) String content){} record Response(String id,String projectId,MockInterviewStatus status,String aiJobId,String followUpAiJobId,long version){static Response of(MockInterviewSession x){return new Response(x.getId(),x.getProjectId(),x.getStatus(),x.getAiJobId(),x.getFollowUpAiJobId(),x.getVersion());}}
 @PostMapping public ResponseEntity<Response> create(@RequestBody @jakarta.validation.Valid Create r){return ResponseEntity.status(202).body(Response.of(s.create(r.projectId())));}
 @GetMapping("/{id}") public Response get(@PathVariable String id){return Response.of(s.get(id));} @GetMapping("/{id}/turns") public List<MockInterviewTurn> turns(@PathVariable String id){return s.turns(id);}
 @PostMapping("/{id}/answers") public ResponseEntity<Response> answer(@PathVariable String id,@RequestHeader(value="If-Match-Version") long v,@RequestBody @jakarta.validation.Valid Answer r){return ResponseEntity.status(HttpStatus.ACCEPTED).body(Response.of(s.answer(id,r.content(),v)));}
 @PostMapping("/{id}/transition") public Response transition(@PathVariable String id,@RequestHeader(value="If-Match-Version") long v,@RequestBody @jakarta.validation.Valid Transition r){return Response.of(s.transition(id,r.targetStatus(),v));}
}
