package com.jobhub.mockinterview.infrastructure;
import com.jobhub.mockinterview.domain.*; import org.apache.ibatis.annotations.*; import java.util.*;
@Mapper public interface MockInterviewMapper {
 @Insert("INSERT INTO mock_interview_session (id,project_id,status,ai_job_id,project_snapshot,created_at,updated_at,version) VALUES (#{id},#{projectId},#{status},#{aiJobId},#{projectSnapshot},#{createdAt},#{updatedAt},0)") int insert(MockInterviewSession s);
 @Select("SELECT id,project_id AS projectId,status,ai_job_id AS aiJobId,follow_up_ai_job_id AS followUpAiJobId,project_snapshot AS projectSnapshot,created_at AS createdAt,updated_at AS updatedAt,version FROM mock_interview_session WHERE id=#{id}") MockInterviewSession selectById(String id);
 @Update("UPDATE mock_interview_session SET ai_job_id=#{aiJobId},updated_at=#{now} WHERE id=#{id}") int setAiJobId(@Param("id") String id,@Param("aiJobId") String aiJobId,@Param("now") String now);
 @Update("UPDATE mock_interview_session SET follow_up_ai_job_id=#{aiJobId},updated_at=#{now} WHERE id=#{id}") int setFollowUpAiJobId(@Param("id") String id,@Param("aiJobId") String aiJobId,@Param("now") String now);
 @Update("UPDATE mock_interview_session SET follow_up_ai_job_id=NULL,updated_at=#{now} WHERE id=#{id} AND follow_up_ai_job_id=#{aiJobId}") int clearFollowUpAiJobId(@Param("id") String id,@Param("aiJobId") String aiJobId,@Param("now") String now);
 @Update("UPDATE mock_interview_session SET status='ACTIVE',updated_at=#{now},version=version+1 WHERE id=#{id} AND status='DRAFT'") int activate(@Param("id") String id,@Param("now") String now);
 @Update("UPDATE mock_interview_session SET status=#{status},updated_at=#{now},version=version+1 WHERE id=#{id} AND status=#{expected} AND version=#{version}") int transition(@Param("id") String id,@Param("status") String status,@Param("expected") String expected,@Param("version") long version,@Param("now") String now);
 @Insert("INSERT INTO mock_interview_turn (id,session_id,turn_number,speaker,content,created_at) VALUES (#{id},#{sessionId},#{turnNumber},#{speaker},#{content},#{createdAt})") int insertTurn(MockInterviewTurn t);
 @Select("SELECT id,session_id AS sessionId,turn_number AS turnNumber,speaker,content,evaluation_ai_job_id AS evaluationAiJobId,evaluation_score AS evaluationScore,evaluation_feedback AS evaluationFeedback,evaluation_rationale AS evaluationRationale,evaluation_completed_at AS evaluationCompletedAt,created_at AS createdAt FROM mock_interview_turn WHERE session_id=#{sessionId} ORDER BY turn_number") List<MockInterviewTurn> selectTurns(String sessionId);
 @Select("SELECT COUNT(*) FROM mock_interview_turn WHERE session_id=#{sessionId}") int countTurns(String sessionId);
 @Select("SELECT COUNT(*) FROM mock_interview_turn WHERE session_id=#{sessionId} AND speaker='USER'") int countUserTurns(String sessionId);
 @Select("SELECT COALESCE(MAX(turn_number), 0) + 1 FROM mock_interview_turn WHERE session_id=#{sessionId}") int nextTurnNumber(String sessionId);
 @Select("SELECT id,session_id AS sessionId,turn_number AS turnNumber,speaker,content,evaluation_ai_job_id AS evaluationAiJobId,evaluation_score AS evaluationScore,evaluation_feedback AS evaluationFeedback,evaluation_rationale AS evaluationRationale,evaluation_completed_at AS evaluationCompletedAt,created_at AS createdAt FROM mock_interview_turn WHERE session_id=#{sessionId} ORDER BY turn_number DESC LIMIT 1") MockInterviewTurn selectLatestTurn(String sessionId);
 @Select("SELECT id,session_id AS sessionId,turn_number AS turnNumber,speaker,content,evaluation_ai_job_id AS evaluationAiJobId,evaluation_score AS evaluationScore,evaluation_feedback AS evaluationFeedback,evaluation_rationale AS evaluationRationale,evaluation_completed_at AS evaluationCompletedAt,created_at AS createdAt FROM mock_interview_turn WHERE id=#{id} AND session_id=#{sessionId}") MockInterviewTurn selectTurn(@Param("id") String id,@Param("sessionId") String sessionId);
 @Update("UPDATE mock_interview_turn SET evaluation_ai_job_id=#{aiJobId} WHERE id=#{turnId} AND session_id=#{sessionId} AND speaker='USER' AND evaluation_ai_job_id IS NULL") int setEvaluationAiJobId(@Param("turnId") String turnId,@Param("sessionId") String sessionId,@Param("aiJobId") String aiJobId);
 @Update("UPDATE mock_interview_turn SET evaluation_score=#{score},evaluation_feedback=#{feedback},evaluation_rationale=#{rationale},evaluation_completed_at=#{completedAt} WHERE id=#{turnId} AND evaluation_ai_job_id=#{aiJobId} AND evaluation_score IS NULL") int saveEvaluation(@Param("turnId") String turnId,@Param("aiJobId") String aiJobId,@Param("score") int score,@Param("feedback") String feedback,@Param("rationale") String rationale,@Param("completedAt") String completedAt);
 @Select("SELECT COUNT(*) FROM mock_interview_turn WHERE evaluation_score IS NOT NULL") int countEvaluatedAnswers();
 @Select("SELECT COUNT(DISTINCT session_id) FROM mock_interview_turn WHERE evaluation_score IS NOT NULL") int countEvaluatedSessions();
 @Select("SELECT AVG(evaluation_score) FROM mock_interview_turn WHERE evaluation_score IS NOT NULL") Double averageEvaluationScore();
 @Select("SELECT evaluation_score AS score,COUNT(*) AS count FROM mock_interview_turn WHERE evaluation_score IS NOT NULL GROUP BY evaluation_score") List<MockInterviewScoreCount> selectScoreDistribution();
 @Select("SELECT session_id AS sessionId,id AS turnId,evaluation_score AS score,COALESCE(evaluation_completed_at,created_at) AS evaluatedAt FROM mock_interview_turn WHERE evaluation_score IS NOT NULL ORDER BY COALESCE(evaluation_completed_at,created_at) DESC,id DESC LIMIT 5") List<MockInterviewRecentScore> selectRecentScores();
 @Update("UPDATE mock_interview_session SET updated_at=#{now},version=version+1 WHERE id=#{id} AND status='ACTIVE' AND version=#{version}") int incrementVersionForAnswer(@Param("id") String id,@Param("version") long version,@Param("now") String now);
 @Update("UPDATE mock_interview_session SET updated_at=#{now},version=version+1 WHERE id=#{id} AND status='ACTIVE' AND follow_up_ai_job_id=#{aiJobId} AND version=#{version}") int incrementVersionForFollowUp(@Param("id") String id,@Param("aiJobId") String aiJobId,@Param("version") long version,@Param("now") String now);
}
