package com.jobhub.interview.infrastructure;
import com.jobhub.interview.domain.*;
import org.apache.ibatis.annotations.*;
import java.util.List;
@Mapper public interface ReminderMapper {
    @Insert("INSERT INTO interview_reminder (id, interview_id, reminder_type, scheduled_at, status, created_at, updated_at, version) VALUES (#{id},#{interviewId},#{reminderType},#{scheduledAt},#{status},#{createdAt},#{updatedAt},#{version})") int insert(Reminder r);
    @Select("SELECT * FROM interview_reminder WHERE interview_id=#{interviewId} ORDER BY scheduled_at") List<Reminder> selectByInterview(@Param("interviewId") String interviewId);
    @Select("SELECT * FROM interview_reminder WHERE id=#{id}") Reminder selectById(@Param("id") String id);
    @Update("UPDATE interview_reminder SET status='CANCELED', failure_reason=NULL, lease_until=NULL, lease_token=NULL, updated_at=#{now}, version=version+1 WHERE interview_id=#{interviewId} AND status IN ('PENDING','PROCESSING','FAILED')") int cancelOpen(@Param("interviewId") String interviewId,@Param("now") String now);
    @Update("UPDATE interview_reminder SET scheduled_at=#{r.scheduledAt}, status=#{r.status}, failure_reason=NULL, lease_until=NULL, lease_token=NULL, updated_at=#{r.updatedAt}, version=version+1 WHERE id=#{r.id} AND version=#{expectedVersion}") int update(@Param("r") Reminder r,@Param("expectedVersion") long expectedVersion);
    @Select("SELECT r.id, r.interview_id AS interviewId, r.reminder_type AS reminderType, r.scheduled_at AS scheduledAt, i.round_name AS roundName FROM interview_reminder r JOIN interview_schedule i ON i.id = r.interview_id WHERE r.scheduled_at <= #{now} AND (r.status='PENDING' OR (r.status='PROCESSING' AND (r.lease_until IS NULL OR r.lease_until <= #{now}))) ORDER BY r.scheduled_at LIMIT 200") List<DueReminderRow> selectDue(@Param("now") String now);
    @Update("UPDATE interview_reminder SET status='PROCESSING', attempt_count=attempt_count+1, lease_until=#{leaseUntil}, lease_token=#{leaseToken}, updated_at=#{now}, version=version+1 WHERE id=#{id} AND scheduled_at <= #{now} AND (status='PENDING' OR (status='PROCESSING' AND (lease_until IS NULL OR lease_until <= #{now})))") int claim(@Param("id") String id,@Param("now") String now,@Param("leaseUntil") String leaseUntil,@Param("leaseToken") String leaseToken);
    @Update("UPDATE interview_reminder SET status='SENT', failure_reason=NULL, lease_until=NULL, lease_token=NULL, updated_at=#{now}, version=version+1 WHERE id=#{id} AND status='PROCESSING' AND lease_token=#{leaseToken}") int markSent(@Param("id") String id,@Param("now") String now,@Param("leaseToken") String leaseToken);
    @Update("UPDATE interview_reminder SET status='FAILED', failure_reason=#{reason}, lease_until=NULL, lease_token=NULL, updated_at=#{now}, version=version+1 WHERE id=#{id} AND status='PROCESSING' AND lease_token=#{leaseToken}") int markFailed(@Param("id") String id,@Param("reason") String reason,@Param("now") String now,@Param("leaseToken") String leaseToken);
    @Update("UPDATE interview_reminder SET status='PENDING', failure_reason=NULL, lease_until=NULL, lease_token=NULL, updated_at=#{now}, version=version+1 WHERE id=#{id} AND status='FAILED' AND version=#{expectedVersion}") int retryFailed(@Param("id") String id,@Param("expectedVersion") long expectedVersion,@Param("now") String now);
}
