package com.jobhub.mockinterview.application;
import com.fasterxml.jackson.databind.ObjectMapper; import com.jobhub.ai.application.AiJobService; import com.jobhub.ai.domain.AiJob; import com.jobhub.ai.domain.AiJobStatus; import com.jobhub.common.error.*; import com.jobhub.common.id.IdGenerator; import com.jobhub.common.time.UtcTime; import com.jobhub.common.version.VersionCheck; import com.jobhub.evidence.domain.ProjectCase; import com.jobhub.evidence.infrastructure.ProjectMapper; import com.jobhub.mockinterview.domain.*; import com.jobhub.mockinterview.infrastructure.MockInterviewMapper; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service public class MockInterviewService {
 private final MockInterviewMapper mapper; private final ProjectMapper projects; private final AiJobService ai; private final IdGenerator ids; private final UtcTime time; private static final ObjectMapper JSON=new ObjectMapper();
 public MockInterviewService(MockInterviewMapper m,ProjectMapper p,AiJobService a,IdGenerator i,UtcTime t){mapper=m;projects=p;ai=a;ids=i;time=t;}
 @Transactional public MockInterviewSession create(String projectId){ ProjectCase p=projects.selectById(projectId); VersionCheck.requireFound(p,"ProjectCase",projectId); String now=time.now(); MockInterviewSession s=new MockInterviewSession(); s.setId(ids.newId());s.setProjectId(projectId);s.setStatus(MockInterviewStatus.DRAFT);s.setProjectSnapshot(snapshot(p));s.setCreatedAt(now);s.setUpdatedAt(now); mapper.insert(s); AiJob job=ai.createMockInterview(s.getId(),s.getProjectSnapshot()); mapper.setAiJobId(s.getId(),job.getId(),time.now()); return get(s.getId()); }
 @Transactional public MockInterviewSession get(String id){ MockInterviewSession s=mapper.selectById(id); VersionCheck.requireFound(s,"MockInterviewSession",id); if(s.getStatus()==MockInterviewStatus.DRAFT && s.getAiJobId()!=null){ AiJob job=ai.get(s.getAiJobId()); if(job.getStatus()==AiJobStatus.SUCCEEDED && mapper.countTurns(id)==0){ var items=job.getItems(); if(items.size()!=1) throw new BusinessRuleException("模拟面试生成结果无效"); var payload=com.jobhub.ai.domain.AiItemPayload.parseList("["+items.get(0).getPayloadJson()+"]").get(0); String now=time.now(); mapper.insertTurn(new MockInterviewTurn(ids.newId(),id,1,"AI",payload.rawText(),now)); mapper.insertTurn(new MockInterviewTurn(ids.newId(),id,2,"AI",payload.rationale(),now)); mapper.activate(id,now); s=mapper.selectById(id); } } return s; }
 public List<MockInterviewTurn> turns(String id){get(id);return mapper.selectTurns(id);}
 @Transactional public MockInterviewTurn answer(String id,String content,long version){MockInterviewSession s=get(id); if(s.getStatus()!=MockInterviewStatus.ACTIVE)throw new IllegalStateTransitionException(s.getStatus().name(),"USER_ANSWERED","仅 ACTIVE 模拟面试可以保存作答"); if(s.getVersion()!=version)throw new VersionConflictException(s.getVersion()); if(mapper.countUserTurns(id)>0)throw new IllegalStateTransitionException(s.getStatus().name(),"USER_ANSWERED","首个追问已保存作答"); String now=time.now(); VersionCheck.requireAffected(mapper.incrementVersionForAnswer(id,version,now),s.getVersion()); MockInterviewTurn turn=new MockInterviewTurn(ids.newId(),id,mapper.nextTurnNumber(id),"USER",content.trim(),now); mapper.insertTurn(turn); return turn;}
 @Transactional public MockInterviewSession transition(String id,MockInterviewStatus target,long version){MockInterviewSession s=get(id); if(!((s.getStatus()==MockInterviewStatus.DRAFT && target==MockInterviewStatus.CANCELED)||(s.getStatus()==MockInterviewStatus.ACTIVE && (target==MockInterviewStatus.COMPLETED||target==MockInterviewStatus.CANCELED)))) throw new IllegalStateTransitionException(s.getStatus().name(),target.name(),"模拟面试只能按专用命令结束或取消"); VersionCheck.requireAffected(mapper.transition(id,target.name(),s.getStatus().name(),version,time.now()),s.getVersion()); if(target==MockInterviewStatus.CANCELED && s.getAiJobId()!=null){AiJob job=ai.get(s.getAiJobId());if(job.getStatus()==AiJobStatus.QUEUED||job.getStatus()==AiJobStatus.RUNNING)ai.cancel(s.getAiJobId());} return get(id);}
 private String snapshot(ProjectCase p){try{return JSON.writeValueAsString(Map.of("title",p.getTitle(),"scenario",p.getScenario(),"approach",p.getApproach(),"problemSolved",p.getProblemSolved(),"result",Optional.ofNullable(p.getResultText()).orElse("")));}catch(Exception e){throw new BusinessRuleException("项目快照序列化失败");}}
}
