package com.jobhub.mockinterview.application;
import com.fasterxml.jackson.databind.ObjectMapper; import com.jobhub.ai.application.AiJobService; import com.jobhub.ai.domain.AiJob; import com.jobhub.ai.domain.AiJobStatus; import com.jobhub.common.error.*; import com.jobhub.common.id.IdGenerator; import com.jobhub.common.time.UtcTime; import com.jobhub.common.version.VersionCheck; import com.jobhub.evidence.domain.ProjectCase; import com.jobhub.evidence.infrastructure.ProjectMapper; import com.jobhub.mockinterview.domain.*; import com.jobhub.mockinterview.infrastructure.MockInterviewMapper; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service public class MockInterviewService {
 private final MockInterviewMapper mapper; private final ProjectMapper projects; private final AiJobService ai; private final IdGenerator ids; private final UtcTime time; private static final ObjectMapper JSON=new ObjectMapper();
 public MockInterviewService(MockInterviewMapper m,ProjectMapper p,AiJobService a,IdGenerator i,UtcTime t){mapper=m;projects=p;ai=a;ids=i;time=t;}
 @Transactional public MockInterviewSession create(String projectId){ ProjectCase p=projects.selectById(projectId); VersionCheck.requireFound(p,"ProjectCase",projectId); String now=time.now(); MockInterviewSession s=new MockInterviewSession(); s.setId(ids.newId());s.setProjectId(projectId);s.setStatus(MockInterviewStatus.DRAFT);s.setProjectSnapshot(snapshot(p));s.setCreatedAt(now);s.setUpdatedAt(now); mapper.insert(s); AiJob job=ai.createMockInterview(s.getId(),s.getProjectSnapshot()); mapper.setAiJobId(s.getId(),job.getId(),time.now()); return get(s.getId()); }
 @Transactional public MockInterviewSession get(String id){ MockInterviewSession s=mapper.selectById(id); VersionCheck.requireFound(s,"MockInterviewSession",id); if(s.getStatus()==MockInterviewStatus.DRAFT && s.getAiJobId()!=null){ AiJob job=ai.get(s.getAiJobId()); if(job.getStatus()==AiJobStatus.SUCCEEDED && mapper.countTurns(id)==0){ var items=job.getItems(); if(items.size()!=1) throw new BusinessRuleException("模拟面试生成结果无效"); var payload=com.jobhub.ai.domain.AiItemPayload.parseList("["+items.get(0).getPayloadJson()+"]").get(0); String now=time.now(); mapper.insertTurn(new MockInterviewTurn(ids.newId(),id,1,"AI",payload.rawText(),now)); mapper.insertTurn(new MockInterviewTurn(ids.newId(),id,2,"AI",payload.rationale(),now)); mapper.activate(id,now); s=mapper.selectById(id); } } if(s.getStatus()==MockInterviewStatus.ACTIVE&&s.getFollowUpAiJobId()!=null){AiJob job=ai.get(s.getFollowUpAiJobId());MockInterviewTurn last=mapper.selectLatestTurn(id);if(job.getStatus()==AiJobStatus.SUCCEEDED&&last!=null&&"USER".equals(last.speaker())&&mapper.incrementVersionForFollowUp(id,job.getId(),s.getVersion(),time.now())==1){var items=job.getItems();if(items.size()!=1)throw new BusinessRuleException("连续追问生成结果无效");var payload=com.jobhub.ai.domain.AiItemPayload.parseList("["+items.get(0).getPayloadJson()+"]").get(0);mapper.insertTurn(new MockInterviewTurn(ids.newId(),id,mapper.nextTurnNumber(id),"AI",payload.rawText(),time.now()));mapper.clearFollowUpAiJobId(id,job.getId(),time.now());s=mapper.selectById(id);}} return s; }
 @Transactional public List<MockInterviewTurn> turns(String id){get(id); for(MockInterviewTurn turn:mapper.selectTurns(id)){hydrateEvaluation(turn);} return mapper.selectTurns(id);}
 @Transactional(readOnly=true) public MockInterviewEvaluationSummary evaluationSummary(){int count=mapper.countEvaluatedAnswers();return new MockInterviewEvaluationSummary(count,mapper.countEvaluatedSessions(),count<2?null:mapper.averageEvaluationScore(),completeDistribution(mapper.selectScoreDistribution()),mapper.selectRecentScores());}
 @Transactional(readOnly=true) public MockInterviewEvaluationTrend evaluationTrend(String from,String to,String compareFrom,String compareTo){
  validateWindow(from,to);validateWindow(compareFrom,compareTo);
  MockInterviewEvaluationWindow current=window(from,to); MockInterviewEvaluationWindow compare=window(compareFrom,compareTo);
  Double delta=current.averageScore()==null||compare.averageScore()==null?null:current.averageScore()-compare.averageScore();
  return new MockInterviewEvaluationTrend(current,compare,delta);
 }
 @Transactional public MockInterviewSession answer(String id,String content,long version){MockInterviewSession s=get(id); if(s.getStatus()!=MockInterviewStatus.ACTIVE)throw new IllegalStateTransitionException(s.getStatus().name(),"USER_ANSWERED","仅 ACTIVE 模拟面试可以保存作答"); if(s.getVersion()!=version)throw new VersionConflictException(s.getVersion()); MockInterviewTurn last=mapper.selectLatestTurn(id);if(last==null||!"AI".equals(last.speaker()))throw new IllegalStateTransitionException(s.getStatus().name(),"USER_ANSWERED","请等待 AI 追问完成后再作答");if(s.getFollowUpAiJobId()!=null){AiJob prior=ai.get(s.getFollowUpAiJobId());if(prior.getStatus()==AiJobStatus.QUEUED||prior.getStatus()==AiJobStatus.RUNNING)throw new IllegalStateTransitionException(s.getStatus().name(),"USER_ANSWERED","连续追问仍在生成中");}String now=time.now(); VersionCheck.requireAffected(mapper.incrementVersionForAnswer(id,version,now),s.getVersion());mapper.insertTurn(new MockInterviewTurn(ids.newId(),id,mapper.nextTurnNumber(id),"USER",content.trim(),now));AiJob job=ai.createMockInterviewFollowUp(id,s.getProjectSnapshot(),last.content(),content.trim());mapper.setFollowUpAiJobId(id,job.getId(),time.now());return mapper.selectById(id);}
 @Transactional public MockInterviewSession evaluate(String id,String turnId,long version){MockInterviewSession s=get(id);if(s.getStatus()==MockInterviewStatus.CANCELED)throw new IllegalStateTransitionException(s.getStatus().name(),"EVALUATE_ANSWER","已取消会话不能评分");if(s.getVersion()!=version)throw new VersionConflictException(s.getVersion());MockInterviewTurn answer=mapper.selectTurn(turnId,id);if(answer==null||!"USER".equals(answer.speaker()))throw new BusinessRuleException("只能对已保存的用户作答评分");if(answer.evaluationAiJobId()!=null)throw new BusinessRuleException("该作答已发起评分");MockInterviewTurn question=mapper.selectTurns(id).stream().filter(t->t.turnNumber()==answer.turnNumber()-1).findFirst().orElseThrow(()->new BusinessRuleException("作答缺少对应追问"));if(!"AI".equals(question.speaker()))throw new BusinessRuleException("作答缺少对应 AI 追问");String now=time.now();VersionCheck.requireAffected(mapper.incrementVersionForAnswer(id,version,now),s.getVersion());AiJob job=ai.createMockInterviewAnswerEvaluation(id,s.getProjectSnapshot(),question.content(),answer.content());if(mapper.setEvaluationAiJobId(turnId,id,job.getId())!=1)throw new BusinessRuleException("该作答已发起评分");return mapper.selectById(id);}
 @Transactional public MockInterviewSession transition(String id,MockInterviewStatus target,long version){MockInterviewSession s=get(id); if(!((s.getStatus()==MockInterviewStatus.DRAFT && target==MockInterviewStatus.CANCELED)||(s.getStatus()==MockInterviewStatus.ACTIVE && (target==MockInterviewStatus.COMPLETED||target==MockInterviewStatus.CANCELED)))) throw new IllegalStateTransitionException(s.getStatus().name(),target.name(),"模拟面试只能按专用命令结束或取消"); VersionCheck.requireAffected(mapper.transition(id,target.name(),s.getStatus().name(),version,time.now()),s.getVersion());cancelIfPending(s.getAiJobId());cancelIfPending(s.getFollowUpAiJobId());if(target==MockInterviewStatus.CANCELED)for(MockInterviewTurn turn:mapper.selectTurns(id))cancelIfPending(turn.evaluationAiJobId()); return get(id);}
 private void cancelIfPending(String jobId){if(jobId==null)return;AiJob job=ai.get(jobId);if(job.getStatus()==AiJobStatus.QUEUED||job.getStatus()==AiJobStatus.RUNNING)ai.cancel(jobId);}
 private void hydrateEvaluation(MockInterviewTurn turn){if(turn.evaluationAiJobId()==null||turn.evaluationScore()!=null)return;AiJob job=ai.get(turn.evaluationAiJobId());if(job.getStatus()!=AiJobStatus.SUCCEEDED)return;var items=job.getItems();if(items.size()!=1)throw new BusinessRuleException("作答评分结果无效");var payload=com.jobhub.ai.domain.AiItemPayload.parseList("["+items.get(0).getPayloadJson()+"]").get(0);int score;try{score=Integer.parseInt(payload.normalizedName());}catch(Exception ex){throw new BusinessRuleException("作答评分分值无效");}if(score<1||score>5||payload.rawText()==null||payload.rawText().isBlank()||payload.rationale()==null||payload.rationale().isBlank())throw new BusinessRuleException("作答评分结果无效");mapper.saveEvaluation(turn.id(),job.getId(),score,payload.rawText(),payload.rationale(),time.now());}
 private MockInterviewEvaluationWindow window(String from,String to){int count=mapper.countEvaluatedAnswersInWindow(from,to);return new MockInterviewEvaluationWindow(from,to,count,mapper.countEvaluatedSessionsInWindow(from,to),count<2?null:mapper.averageEvaluationScoreInWindow(from,to),completeDistribution(mapper.selectScoreDistributionInWindow(from,to)));}
 private List<MockInterviewScoreCount> completeDistribution(List<MockInterviewScoreCount> scores){Map<Integer,Integer> byScore=new HashMap<>();for(MockInterviewScoreCount score:scores)byScore.put(score.score(),score.count());List<MockInterviewScoreCount> distribution=new ArrayList<>();for(int score=1;score<=5;score++)distribution.add(new MockInterviewScoreCount(score,byScore.getOrDefault(score,0)));return distribution;}
 private void validateWindow(String from,String to){try{if(from==null||to==null||!java.time.Instant.parse(from).isBefore(java.time.Instant.parse(to)))throw new IllegalArgumentException();}catch(Exception e){throw new BusinessRuleException("评分窗口必须是开始早于结束的完整 UTC 时间点");}}
 private String snapshot(ProjectCase p){try{return JSON.writeValueAsString(Map.of("title",p.getTitle(),"scenario",p.getScenario(),"approach",p.getApproach(),"problemSolved",p.getProblemSolved(),"result",Optional.ofNullable(p.getResultText()).orElse("")));}catch(Exception e){throw new BusinessRuleException("项目快照序列化失败");}}
}
