package com.jobhub.ai.domain;

public enum AiJobType {
	JD_EXTRACTION,
	RESUME_DRAFT,
	QUESTION_CLASSIFICATION,
	ANSWER_QUALITY_ANALYSIS,
	TASK_SUGGESTION,
	MOCK_INTERVIEW,
	MOCK_INTERVIEW_FOLLOW_UP
}
